# Example device definitions for SNMP Collector.
localhost:
  ip: 127.0.0.1
  port: 161
  poll_interval: 120
  timeout: 15000
  retries: 2
  exponential_timeout: false
  version: 3
  v3_credentials:
    - username: testUser
      authentication_protocol: sha512
      authentication_passphrase: testAuth
      privacy_protocol: aes
      privacy_passphrase: testPriv
  device_groups:
    - linux
  max_concurrent_polls: 4
  use_getbulk: true